# Generated by Django 5.0.7 on 2024-07-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="date_of_payment",
            field=models.DateTimeField(
                blank=True,
                help_text="Укажите дату оплаты",
                null=True,
                verbose_name="Дата оплаты",
            ),
        ),
    ]
