# Generated by Django 5.0.7 on 2024-07-23 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_subscriptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptions",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriber",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
