# Generated by Django 5.0.7 on 2024-07-26 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_alter_lesson_options"),
        ("users", "0005_alter_subscriptions_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_amount",
            field=models.PositiveIntegerField(verbose_name="введите сумму оплаты"),
        ),
        migrations.AlterField(
            model_name="subscriptions",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscribed_course",
                to="courses.course",
                verbose_name="курс, на который создана подписка",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptions",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriber",
                to=settings.AUTH_USER_MODEL,
                verbose_name="подписчик",
            ),
        ),
    ]
