# Generated by Django 5.0.7 on 2024-07-29 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_alter_lesson_options"),
        ("users", "0006_alter_payments_payment_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="link",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="Cсылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="session_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Id сессии"
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="Введите оплаченный курс",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course",
                to="courses.course",
                verbose_name="Оплаченный курс",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                help_text="Введите оплаченный урок",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson",
                to="courses.lesson",
                verbose_name="Оплаченный урок",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="payment_amount",
            field=models.PositiveIntegerField(
                help_text="Введите сумму оплаты", verbose_name="введите сумму оплаты"
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="user",
            field=models.ForeignKey(
                help_text="Введите пользователя, внесшего оплату",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь внесший оплату",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptions",
            name="course",
            field=models.ForeignKey(
                help_text="введите ID курса подписки",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscribed_course",
                to="courses.course",
                verbose_name="курс, на который создана подписка",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptions",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="введите ID подписчика",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriber",
                to=settings.AUTH_USER_MODEL,
                verbose_name="подписчик",
            ),
        ),
    ]
