# Generated by Django 5.0.7 on 2024-07-11 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                help_text="Введите курс",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="courses.course",
                verbose_name="Курс",
            ),
        ),
    ]
