# Generated by Django 5.0.7 on 2024-07-26 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_alter_lesson_course"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"verbose_name": "урок", "verbose_name_plural": "уроки"},
        ),
    ]
